# Darwin Platform Services
services:
  # Feature Store Service
  feature-store:
    enabled: true
    replicaCount: 1
    serviceName: darwin-ofs-v2
    image:
      registry: localhost:5000
      name: darwin-ofs-v2
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 8080
    ingress:
      enabled: false
    autoscaling:
      enabled: false

  feature-store-admin:
    enabled: true
    replicaCount: 1
    serviceName: darwin-ofs-v2-admin
    image:
      registry: localhost:5000
      name: darwin-ofs-v2-admin
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 8080
    ingress:
      enabled: false
    autoscaling:
      enabled: false

  feature-store-consumer:
    enabled: true
    replicaCount: 1
    serviceName: darwin-ofs-v2-consumer
    image:
      registry: localhost:5000
      name: darwin-ofs-v2-consumer
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 8080
    ingress:
      enabled: false
    autoscaling:
      enabled: false

  chronos:
    enabled: true
    replicaCount: 1
    serviceName: chronos
    image:
      registry: localhost:5000
      name: chronos
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 8000
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      hosts:
        - host: localhost
          paths:
            - path: /chronos(/|$)(.*)
              pathType: ImplementationSpecific
    autoscaling:
      enabled: false
    extraEnvVars:
      - name: ENV
        value: "local"
      - name: DEPLOYMENT_TYPE
        value: "container"
      - name: AWS_ACCESS_KEY_ID
        value: "test"
      - name: AWS_SECRET_ACCESS_KEY
        value: "test"
      - name: AWS_DEFAULT_REGION
        value: "us-east-1"

  chronos-consumer:
    enabled: true
    replicaCount: 1
    serviceName: chronos-consumer
    image:
      registry: localhost:5000
      name: chronos-consumer
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 8000
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      hosts:
        - host: localhost
          paths:
            - path: /chronos-consumer(/|$)(.*)
              pathType: ImplementationSpecific
    autoscaling:
      enabled: false
    extraEnvVars:
      - name: ENV
        value: "local"
      - name: DEPLOYMENT_TYPE
        value: "container"
      - name: AWS_ACCESS_KEY_ID
        value: "test"
      - name: AWS_SECRET_ACCESS_KEY
        value: "test"
      - name: AWS_DEFAULT_REGION
        value: "us-east-1"

  # Workflow Orchestration Service
  workflow:
    enabled: true
    replicaCount: 1
    image:
      repository: darwin-workflow
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 8081
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: darwin-workflow.local
          paths:
            - path: /
              pathType: Prefix
    autoscaling:
      enabled: false

  # Compute Orchestration Service
  compute:
    enabled: true
    replicaCount: 1
    image:
      repository: darwin-compute
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 8082
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: darwin-compute.local
          paths:
            - path: /
              pathType: Prefix
    autoscaling:
      enabled: false

    # Compute Orchestration Service
  mlflow-lib:
    serviceName: darwin-mlflow
    enabled: true
    replicaCount: 1
    image:
      name: darwin-mlflow
      repository: darwin-mlflow
      registry: localhost:5000
      tag: latest
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 8080
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: darwin-mlflow.local
          paths:
            - path: /
              pathType: Prefix
    autoscaling:
      enabled: false
    extraEnvVars:
      - name: ENV
        value: "darwin-local"
      - name: CONFIG_SERVICE_MYSQL_MASTERHOST
        value: "darwin-mysql"
      - name: CONFIG_SERVICE_MYSQL_DATABASE
        value: "darwin_mlflow"
      - name: VAULT_SERVICE_MYSQL_USERNAME
        value: "darwin"
      - name: VAULT_SERVICE_MYSQL_PASSWORD
        value: "password"
      - name: VAULT_SERVICE_ADMIN_USERNAME
        value: "darwin"
      - name: VAULT_SERVICE_ADMIN_PASSWORD
        value: "password"
      - name: CONFIG_SERVICE_MYSQL_AUTH_DATABASE
        value: "darwin_mlflow_auth"
      - name: MLFLOW_S3_BUCKET
        value: "darwin-mlflow"
      - name: AWS_ACCESS_KEY_ID
        value: "test"
      - name: AWS_SECRET_ACCESS_KEY
        value: "test"
      - name: AWS_DEFAULT_REGION
        value: "us-east-1"

  mlflow-app:
    serviceName: darwin-mlflow-app
    enabled: true
    replicaCount: 1
    image:
      name: darwin-mlflow-app
      repository: darwin-mlflow
      registry: localhost:5000
      tag: latest
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 8000
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: darwin-mlflow-app.local
          paths:
            - path: /
              pathType: Prefix
    autoscaling:
      enabled: false
    extraEnvVars:
      - name: ENV
        value: "darwin-local"
      - name: CONFIG_SERVICE_MYSQL_MASTERHOST
        value: "darwin-mysql"
      - name: CONFIG_SERVICE_MYSQL_DATABASE
        value: "darwin_mlflow"
      - name: VAULT_SERVICE_MYSQL_USERNAME
        value: "darwin"
      - name: VAULT_SERVICE_MYSQL_PASSWORD
        value: "password"
      - name: VAULT_SERVICE_ADMIN_USERNAME
        value: "darwin"
      - name: VAULT_SERVICE_ADMIN_PASSWORD
        value: "password"
      - name: VAULT_SERVICE_MLFLOW_ADMIN_USERNAME
        value: "darwin"
      - name: VAULT_SERVICE_MLFLOW_ADMIN_PASSWORD
        value: "password"
      - name: MLFLOW_UI_URL
        value: "http://darwin-mlflow-lib:8080"
      - name: MLFLOW_APP_LAYER_URL
        value: "http://darwin-mlflow-lib:8080"
      - name: MLFLOW_APP_BASE_PATH
        value: ""
      - name: DARWIN_MYSQL_HOST
        value: "darwin-mysql"
      - name: MYSQL_PORT
        value: "3306"
      - name: MLFLOW_S3_BUCKET
        value: "darwin-mlflow"
      - name: AWS_ACCESS_KEY_ID
        value: "test"
      - name: AWS_SECRET_ACCESS_KEY
        value: "test"
      - name: AWS_DEFAULT_REGION
        value: "us-east-1"

# Ingress Configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  host: "localhost"
  # Path-based routing: /service/endpoint -> service:port/endpoint
  paths:
    - path: "/feature-store(/|$)(.*)"
      service: "feature-store"
      port: 8080
    - path: "/feature-store-admin(/|$)(.*)"
      service: "feature-store-admin"
      port: 8080
    - path: "/feature-store-consumer(/|$)(.*)"
      service: "feature-store-consumer"
      port: 8080
    - path: "/mlflow-lib(/|$)(.*)"
      service: "mlflow-lib"
      port: 8080
    - path: "/mlflow-app(/|$)(.*)"
      service: "mlflow-app"
      port: 8000
