{{- if .Values.airflow.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-operators
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "darwin.labels" . | nindent 4 }}
    app.kubernetes.io/component: airflow-operators
data:
  darwin_operator.py: |
{{ .Files.Get "files/operators/darwin_operator.py" | indent 4 }}
  pelican_operator.py: |
{{ .Files.Get "files/operators/pelican_operator.py" | indent 4 }}
  workflow_operator.py: |
{{ .Files.Get "files/operators/workflow_operator.py" | indent 4 }}
{{- end }}

