{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mysql-init
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "darwin.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
data:
  01-create-airflow-db.sql: |
    CREATE DATABASE IF NOT EXISTS airflow;
    GRANT ALL PRIVILEGES ON airflow.* TO 'root'@'%';
    FLUSH PRIVILEGES;
  02-create-mlflow-db.sql: |
    CREATE DATABASE IF NOT EXISTS darwin_mlflow;
    CREATE DATABASE IF NOT EXISTS darwin_mlflow_auth;
    GRANT ALL PRIVILEGES ON darwin_mlflow.* TO 'darwin'@'%';
    GRANT ALL PRIVILEGES ON darwin_mlflow_auth.* TO 'darwin'@'%';
    FLUSH PRIVILEGES;
{{- end }}
