applications:
  - application: darwin-compute
    base-path: darwin-compute
    path: .
    base-image: darwin/python:3.9.7-pip-bookworm-slim
    env:
      - name: SERVICE_NAME
        value: "darwin-compute"
  
  - application: darwin-cluster-manager
    base-path: darwin-cluster-manager
    path: .
    base-image: darwin/golang:1.18-bookworm-slim
    env:
      - name: SERVICE_NAME
        value: "darwin-cluster-manager"
