[metadata]
name = commons
version = 0.1.0
description = Common utilities and models for darwin-workflow

[options]
package_dir =
    commons = .
packages = 
    commons
    commons.constant
    commons.dao
    commons.kafka
    commons.models
    commons.utils
python_requires = >=3.6
zip_safe = no

