{{- if and .Values.darwinFeatureStore.enabled .Values.darwinFeatureStore.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "darwin.fullname" . }}-feature-store
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "darwin.labels" . | nindent 4 }}
    app.kubernetes.io/component: feature-store
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "darwin.fullname" . }}-feature-store
  minReplicas: {{ .Values.darwinFeatureStore.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.darwinFeatureStore.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.darwinFeatureStore.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.darwinFeatureStore.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
{{- end }}
